# Generated by Django 6.0.5 on 2026-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem_customer_phone_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('old_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Старая цена')),
                ('image', models.URLField(max_length=500, verbose_name='Ссылка на изображение')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
